- id: 1
  name: ごちゃまぜサラダ
  category: サラダ
  energy: 0
  ingredients: []

- id: 2
  name: ヤドンテールのペッパーサラダ
  category: サラダ
  energy: 8169
  ingredients:
    - { ingredientId: 6,  quantity: 10 }
    - { ingredientId: 10, quantity: 15 }
    - { ingredientId: 14, quantity: 10 }

- id: 3
  name: キノコのほうしサラダ
  category: サラダ
  energy: 5859
  ingredients:
    - { ingredientId: 2,  quantity: 17 }
    - { ingredientId: 10, quantity: 8 }
    - { ingredientId: 12, quantity: 8 }

- id: 4
  name: ゆきかきシーザーサラダ
  category: サラダ
  energy: 1898
  ingredients:
    - { ingredientId: 8, quantity: 10 }
    - { ingredientId: 7, quantity: 6 }

- id: 5
  name: くいしんぼうポテトサラダ
  category: サラダ
  energy: 5040
  ingredients:
    - { ingredientId: 4, quantity: 14 }
    - { ingredientId: 3, quantity: 9 }
    - { ingredientId: 7, quantity: 7 }
    - { ingredientId: 5, quantity: 6 }

- id: 6
  name: うるおいとうふサラダ
  category: サラダ
  energy: 3113
  ingredients:
    - { ingredientId: 15, quantity: 15 }
    - { ingredientId: 12, quantity: 9 }

- id: 7
  name: ばかぢからワイルドサラダ
  category: サラダ
  energy: 3046
  ingredients:
    - { ingredientId: 7,  quantity: 9 }
    - { ingredientId: 11, quantity: 6 }
    - { ingredientId: 3,  quantity: 5 }
    - { ingredientId: 4,  quantity: 3 }

- id: 8
  name: マメハムサラダ
  category: サラダ
  energy: 978
  ingredients: [{ ingredientId: 7, quantity: 8 }]

- id: 9
  name: あんみんトマトサラダ
  category: サラダ
  energy: 1045
  ingredients: [{ ingredientId: 12, quantity: 8 }]

- id: 10
  name: モーモーカプレーゼ
  category: サラダ
  energy: 2942
  ingredients:
    - { ingredientId: 8,  quantity: 12 }
    - { ingredientId: 12, quantity: 6 }
    - { ingredientId: 10, quantity: 5 }

- id: 11
  name: ムラっけチョコミートサラダ
  category: サラダ
  energy: 3665
  ingredients:
    - { ingredientId: 13, quantity: 14 }
    - { ingredientId: 7,  quantity: 9 }

- id: 12
  name: オーバーヒートサラダ
  category: サラダ
  energy: 5225
  ingredients:
    - { ingredientId: 6,  quantity: 17 }
    - { ingredientId: 11, quantity: 10 }
    - { ingredientId: 12, quantity: 8 }

- id: 13
  name: とくせんリンゴサラダ
  category: サラダ
  energy: 855
  ingredients: [{ ingredientId: 5, quantity: 8 }]

- id: 14
  name: めんえきねぎサラダ
  category: サラダ
  energy: 2845
  ingredients:
    - { ingredientId: 11, quantity: 5 }
    - { ingredientId: 1,  quantity: 10 }

- id: 15
  name: メロメロりんごのチーズサラダ
  category: サラダ
  energy: 2655
  ingredients:
    - { ingredientId: 5,  quantity: 15 }
    - { ingredientId: 8,  quantity: 5 }
    - { ingredientId: 10, quantity: 3 }

- id: 16
  name: ニンジャサラダ
  category: サラダ
  energy: 11659
  ingredients:
    - { ingredientId: 11, quantity: 11 }
    - { ingredientId: 15, quantity: 19 }
    - { ingredientId: 2,  quantity: 12 }
    - { ingredientId: 1,  quantity: 15 }

- id: 17
  name: ねっぷうとうふサラダ
  category: サラダ
  energy: 2114
  ingredients:
    - { ingredientId: 6,  quantity: 6 }
    - { ingredientId: 15, quantity: 10 }

- id: 18
  name: ワカクササラダ
  category: サラダ
  energy: 11393
  ingredients:
    - { ingredientId: 10, quantity: 22 }
    - { ingredientId: 16, quantity: 17 }
    - { ingredientId: 12, quantity: 14 }
    - { ingredientId: 4,  quantity: 9 }

- id: 19
  name: めいそうスイートサラダ
  category: サラダ
  energy: 7675
  ingredients:
    - { ingredientId: 5,  quantity: 21 }
    - { ingredientId: 9,  quantity: 16 }
    - { ingredientId: 16, quantity: 12 }

- id: 20
  name: みだれづきコーンサラダ
  category: サラダ
  energy: 2785
  ingredients:
    - { ingredientId: 16, quantity: 9 }
    - { ingredientId: 10, quantity: 8 }

- id: 21
  name: クロスチョップドサラダ
  category: サラダ
  energy: 8755
  ingredients:
    - { ingredientId: 3,  quantity: 20 }
    - { ingredientId: 7,  quantity: 15 }
    - { ingredientId: 16, quantity: 11 }
    - { ingredientId: 12, quantity: 10 }

- id: 22
  name: まけんきコーヒーサラダ
  category: サラダ
  energy: 20218
  ingredients:
    - { ingredientId: 17, quantity: 28 }
    - { ingredientId: 7,  quantity: 28 }
    - { ingredientId: 10, quantity: 22 }
    - { ingredientId: 4,  quantity: 22 }

- id: 23
  name: はなふぶきミモザサラダ
  category: サラダ
  energy: 11881
  ingredients:
    - { ingredientId: 3,  quantity: 25 }
    - { ingredientId: 10, quantity: 17 }
    - { ingredientId: 4,  quantity: 15 }
    - { ingredientId: 7,  quantity: 12 }

- id: 24
  name: りんごさんヨーグルトサラダ
  category: サラダ
  energy: 19293
  ingredients:
    - { ingredientId: 3,  quantity: 35 }
    - { ingredientId: 5,  quantity: 28 }
    - { ingredientId: 12, quantity: 23 }
    - { ingredientId: 8,  quantity: 18 }
