- id: 1
  name: キーのみ          # ノーマル
  energy: 28
- id: 2
  name: ヒメリのみ        # ほのお
  energy: 27
- id: 3
  name: オレンのみ        # みず
  energy: 31
- id: 4
  name: ウブのみ          # でんき
  energy: 25
- id: 5
  name: ドリのみ          # くさ
  energy: 30
- id: 6
  name: チーゴのみ        # こおり
  energy: 32
- id: 7
  name: クラボのみ        # かくとう
  energy: 27
- id: 8
  name: カゴのみ          # どく
  energy: 32
- id: 9
  name: フィラのみ        # じめん
  energy: 29
- id: 10
  name: シーヤのみ        # ひこう
  energy: 24
- id: 11
  name: マゴのみ          # エスパー
  energy: 26
- id: 12
  name: ラムのみ          # むし
  energy: 24
- id: 13
  name: オボンのみ        # いわ
  energy: 30
- id: 14
  name: ブリーのみ        # ゴースト
  energy: 26
- id: 15
  name: ヤチェのみ        # ドラゴン
  energy: 35
- id: 16
  name: ウイのみ          # あく
  energy: 31
- id: 17
  name: ベリブのみ        # はがね
  energy: 33
- id: 18
  name: モモンのみ        # フェアリー
  energy: 26
