- id: 1
  majorclass: エナジーチャージ
  minorclass: エナジーチャージS
  name: エナジーチャージS

- id: 2
  majorclass: エナジーチャージ
  minorclass: エナジーチャージS
  name: エナジーチャージS(ランダム)

- id: 3
  majorclass: エナジーチャージ
  minorclass: エナジーチャージS
  name: たくわえる(エナジーチャージS)

- id: 4
  majorclass: エナジーチャージ
  minorclass: エナジーチャージM
  name: エナジーチャージM

- id: 5
  majorclass: エナジーチャージ
  minorclass: エナジーチャージM
  name: ナイトメア(エナジーチャージM)

- id: 6
  majorclass: ゆめのかけらゲット
  minorclass: ゆめのかけらゲットS
  name: ゆめのかけらゲットS

- id: 7
  majorclass: ゆめのかけらゲット
  minorclass: ゆめのかけらゲットS
  name: ゆめのかけらゲットS(ランダム)

- id: 8
  majorclass: げんき回復
  minorclass: げんきエールS
  name: げんきエールS

- id: 9
  majorclass: げんき回復
  minorclass: げんきチャージS
  name: げんきチャージS

- id: 10
  majorclass: げんき回復
  minorclass: げんきチャージS
  name: つきのひかり(げんきチャージS)

- id: 11
  majorclass: げんき回復
  minorclass: げんきオールS
  name: げんきオールS

- id: 12
  majorclass: げんき回復
  minorclass: げんきオールS
  name: みかづきのいのり(げんきオールS)

- id: 13
  majorclass: おてつだいサポート
  minorclass: おてつだいサポートS
  name: おてつだいサポートS

- id: 14
  majorclass: 食材ゲット
  minorclass: 食材ゲットS
  name: 食材ゲットS

- id: 15
  majorclass: 料理パワーアップ
  minorclass: 料理パワーアップS
  name: 料理パワーアップS

- id: 16
  majorclass: ゆびをふる
  minorclass: ゆびをふる
  name: ゆびをふる

- id: 17
  majorclass: 料理チャンス
  minorclass: 料理チャンスS
  name: 料理チャンスS

- id: 18
  majorclass: おてつだいブースト
  minorclass: おてつだいブースト
  name: おてつだいブースト(でんき)

- id: 19
  majorclass: おてつだいブースト
  minorclass: おてつだいブースト
  name: おてつだいブースト(ほのお)

- id: 20
  majorclass: おてつだいブースト
  minorclass: おてつだいブースト
  name: おてつだいブースト(みず)

- id: 21
  majorclass: きのみバースト
  minorclass: きのみバースト
  name: きのみバースト

- id: 22
  majorclass: きのみバースト
  minorclass: きのみバースト
  name: ばけのかわ(きのみバースト)

- id: 23
  majorclass: スキルコピー
  minorclass: スキルコピー
  name: へんしん(スキルコピー)

- id: 24
  majorclass: スキルコピー
  minorclass: スキルコピー
  name: ものまね(スキルコピー)