export const NATURES = [
    { id: 1, name: 'さみしがり', up: 'おてつだいスピード', down: 'げんき回復量' },
    { id: 2, name: 'いじっぱり', up: 'おてつだいスピード', down: '食材おてつだい確率' },
    { id: 3, name: 'やんちゃ', up: 'おてつだいスピード', down: 'メインスキル発生確率' },
    { id: 4, name: 'ゆうかん', up: 'おてつだいスピード', down: 'EXP獲得量' },
    { id: 5, name: 'ずぶとい', up: 'げんき回復量', down: 'おてつだいスピード' },
    { id: 6, name: 'わんぱく', up: 'げんき回復量', down: '食材おてつだい確率' },
    { id: 7, name: 'のうてんき', up: 'げんき回復量', down: 'メインスキル発生確率' },
    { id: 8, name: 'のんき', up: 'げんき回復量', down: 'EXP獲得量' },
    { id: 9, name: 'ひかえめ', up: '食材おてつだい確率', down: 'おてつだいスピード' },
    { id: 10, name: 'おっとり', up: '食材おてつだい確率', down: 'げんき回復量' },
    { id: 11, name: 'うっかりや', up: '食材おてつだい確率', down: 'メインスキル発生確率' },
    { id: 12, name: 'れいせい', up: '食材おてつだい確率', down: 'EXP獲得量' },
    { id: 13, name: 'おだやか', up: 'メインスキル発生確率', down: 'おてつだいスピード' },
    { id: 14, name: 'おとなしい', up: 'メインスキル発生確率', down: 'げんき回復量' },
    { id: 15, name: 'しんちょう', up: 'メインスキル発生確率', down: '食材おてつだい確率' },
    { id: 16, name: 'なまいき', up: 'メインスキル発生確率', down: 'EXP獲得量' },
    { id: 17, name: 'おくびょう', up: 'EXP獲得量', down: 'おてつだいスピード' },
    { id: 18, name: 'せっかち', up: 'EXP獲得量', down: 'げんき回復量' },
    { id: 19, name: 'ようき', up: 'EXP獲得量', down: '食材おてつだい確率' },
    { id: 20, name: 'むじゃき', up: 'EXP獲得量', down: 'メインスキル発生確率' },
    { id: 21, name: 'がんばりや', up: null, down: null },
    { id: 22, name: 'すなお', up: null, down: null },
    { id: 23, name: 'てれや', up: null, down: null },
    { id: 24, name: 'きまぐれ', up: null, down: null },
    { id: 25, name: 'まじめ', up: null, down: null },
  ] as const;